#!/usr/bin/env python
"""Скрипт для создания файлов переводов без использования gettext tools."""
import os
import re
from pathlib import Path
from collections import OrderedDict

BASE_DIR = Path(__file__).resolve().parent
LOCALE_DIR = BASE_DIR / "locale"

# Создаем структуру директорий
(LOCALE_DIR / "en" / "LC_MESSAGES").mkdir(parents=True, exist_ok=True)
(LOCALE_DIR / "uz" / "LC_MESSAGES").mkdir(parents=True, exist_ok=True)

# Полный словарь переводов на английский
EN_TRANSLATIONS = {
    # Forms
    "Телефон": "Phone",
    "Пароль": "Password",
    "Повторите пароль": "Repeat password",
    "Имя": "Name",
    "Пользователь с таким телефоном уже есть.": "User with this phone number already exists.",
    "Пароли не совпадают.": "Passwords do not match.",
    "Услуга": "Service",
    "Комментарий": "Comment",
    "Пожелания": "Wishes",
    "Площадь (м²)": "Area (m²)",
    "Введите площадь": "Enter area",
    "Количество часов": "Number of hours",
    "Введите количество часов": "Enter number of hours",
    "Количество единиц": "Number of items",
    "Введите количество": "Enter quantity",
    "Заполните поле для расчета.": "Fill in the field for calculation.",
    "Оценка (1-5)": "Rating (1-5)",
    "Текст отзыва": "Review text",
    "Расскажите о впечатлении": "Tell us about your experience",
    "Статус": "Status",
    "Все статусы": "All statuses",
    "Приоритет": "Priority",
    "Все приоритеты": "All priorities",
    "Оператор": "Operator",
    "Все операторы": "All operators",
    "Телефон клиента": "Client phone",
    "Ответственный оператор": "Assigned operator",
    "Внутренние заметки": "Internal notes",
    "Внутренние заметки для операторов...": "Internal notes for operators...",
    "Не назначен": "Not assigned",
    "Внутренний комментарий": "Internal comment",
    "Заметки": "Notes",
    "Контекст общения, важные детали": "Communication context, important details",
    "Email": "Email",
    "Telegram": "Telegram",
    "Instagram": "Instagram",
    "Сообщение": "Message",
    "Ваше сообщение...": "Your message...",
    "Укажите номер телефона.": "Please provide a phone number.",
    "Внутренние заметки...": "Internal notes...",
    
    # Models
    "Администратор": "Administrator",
    "Клиент": "Client",
    "Роль": "Role",
    "Название": "Title",
    "Базовая цена": "Base price",
    "Базовая цена или цена за единицу": "Base price or price per unit",
    "Краткое описание": "Short description",
    "Детальное описание": "Detailed description",
    "Полное описание услуги": "Full service description",
    "История и достижения": "History and achievements",
    "История услуги, достижения, статистика": "Service history, achievements, statistics",
    "Тип расчета цены": "Price calculation type",
    "Единица измерения": "Unit of measurement",
    "м², час, шт. и т.д.": "m², hour, pcs., etc.",
    "Минимальная цена": "Minimum price",
    "Минимальная стоимость услуги": "Minimum service cost",
    "Услуга": "Service",
    "Услуги": "Services",
    "Фиксированная цена": "Fixed price",
    "За м²": "Per m²",
    "За час": "Per hour",
    "За единицу": "Per item",
    "Индивидуальный расчет": "Custom calculation",
    "Последний заказ": "Last order",
    "Клиент": "Client",
    "Клиенты": "Clients",
    "Новая": "New",
    "Принята": "Accepted",
    "В работе": "In progress",
    "Завершена": "Completed",
    "Отменена": "Cancelled",
    "Обычный": "Normal",
    "Высокий": "High",
    "CRM клиент": "CRM client",
    "Рассчитанная цена": "Calculated price",
    "Цена, рассчитанная на основе параметров": "Price calculated based on parameters",
    "Заявка": "Order",
    "Заявки": "Orders",
    "Комментарий к заявке": "Order comment",
    "Комментарии к заявкам": "Order comments",
    "Отзыв": "Review",
    "Отзывы": "Reviews",
    "Заявка обратной связи": "Contact request",
    "Заявки обратной связи": "Contact requests",
    "Связались": "Contacted",
    "Закрыта": "Closed",
    
    # Views messages
    "Вы успешно вышли из системы.": "You have successfully logged out.",
    "Заявка создана. Мы свяжемся с вами в ближайшее время.": "Order created. We will contact you soon.",
    "Отзыв доступен после завершения заявки.": "Review is available after order completion.",
    "Вы уже оставили отзыв для этой заявки.": "You have already left a review for this order.",
    "Спасибо за обратную связь!": "Thank you for your feedback!",
    "Вы успешно зарегистрированы и вошли в систему.": "You have successfully registered and logged in.",
    "Комментарий добавлен.": "Comment added.",
    "Заявка успешно обновлена.": "Order successfully updated.",
    "Данные клиента успешно обновлены.": "Client data successfully updated.",
    "Спасибо! Ваша заявка отправлена. Мы свяжемся с вами в ближайшее время.": "Thank you! Your request has been sent. We will contact you soon.",
    "Заявка обновлена.": "Request updated.",
    
    # Templates
    "Сервисные услуги": "Service services",
    "Переключить тему": "Toggle theme",
    "Профессиональные сервисные услуги": "Professional services",
    "Быстро, качественно, надежно. Мы заботимся о вашем комфорте.": "Fast, quality, reliable. We care about your comfort.",
    "Оставить заявку": "Submit request",
    "Посмотреть услуги": "View services",
    "Довольных клиентов": "Satisfied clients",
    "Выполненных заказов": "Completed orders",
    "Лет на рынке": "Years in business",
    "Наши услуги": "Our services",
    "Наша работа": "Our work",
    "Фото работ": "Work photos",
    "До и после": "Before and after",
    "Результаты": "Results",
    "Готовы начать?": "Ready to start?",
    "Посмотрите наш полный каталог услуг и выберите то, что вам нужно": "Browse our full catalog of services and choose what you need",
    "Перейти к каталогу": "Go to catalog",
    "Больше услуг": "More services",
    "Аккаунт": "Account",
    "Мои заявки": "My orders",
    "Выйти": "Log out",
    "Войти": "Log in",
    "Регистрация": "Sign up",
    "Все права защищены.": "All rights reserved.",
    "Услуги": "Services",
    "Минималистичный сервисный каталог": "Minimalist service catalog",
    "Выбирайте услуги, оставляйте заявки и отслеживайте статус без лишнего шума.": "Choose services, submit requests and track status without unnecessary noise.",
    "Создать заявку": "Create order",
    "Начать": "Get started",
    "Подробнее": "Details",
    "Пока нет активных услуг.": "No active services yet.",
    "Заявка отправлена": "Request sent",
    "Заявка успешно отправлена!": "Request successfully sent!",
    "Мы получили вашу заявку и свяжемся с вами в ближайшее время.": "We have received your request and will contact you soon.",
    "На главную": "Home",
    "Отзыв по заявке": "Order review",
    "Сохранить": "Save",
    "Вход": "Login",
    "Нет аккаунта?": "Don't have an account?",
    "Зарегистрируйтесь": "Sign up",
    "Создать аккаунт": "Create account",
    "Уже есть аккаунт?": "Already have an account?",
    "Новая заявка": "New order",
    "Параметры расчета": "Calculation parameters",
    "Площадь:": "Area:",
    "Количество часов:": "Number of hours:",
    "Количество единиц:": "Number of items:",
    "Рассчитанная стоимость:": "Calculated price:",
    "Заполните форму, и мы свяжемся с вами в ближайшее время": "Fill out the form and we will contact you soon",
    "Необязательно": "Optional",
    "Отправить заявку": "Submit request",
    "Дашборд": "Dashboard",
    "Новые заявки": "New orders",
    "Завершено": "Completed",
    "Новые заявки обратной связи": "New contact requests",
    "Последние заявки": "Recent orders",
    "Все заявки": "All orders",
    "Клиент": "Client",
    "Параметры": "Parameters",
    "Отзыв": "Review",
    "Обновлено": "Updated",
    "Нет данных.": "No data.",
    "Новые клиенты": "New clients",
    "Все клиенты": "All clients",
    "Последние заявки обратной связи": "Recent contact requests",
    "Создано": "Created",
    "Нет заявок.": "No requests.",
    "Заявки обратной связи": "Contact requests",
    "Все статусы": "All statuses",
    "Новая": "New",
    "Фильтр": "Filter",
    "Нет заявок.": "No requests.",
    "Страница": "Page",
    "из": "of",
    "Назад": "Back",
    "Вперёд": "Forward",
    "Заявка обратной связи": "Contact request",
    "Назад к списку": "Back to list",
    "Информация о заявке": "Request information",
    "Телефон:": "Phone:",
    "Статус:": "Status:",
    "Ответственный:": "Assigned to:",
    "Создано:": "Created:",
    "Обновлено:": "Updated:",
    "Управление": "Management",
    "Клиенты": "Clients",
    "Все клиенты": "All clients",
    "Клиенты не найдены.": "Clients not found.",
    "Заявок": "Orders",
    "Статистика": "Statistics",
    "Меню": "Menu",
    "Персональные данные": "Personal data",
    "Права доступа": "Access rights",
    "Системная информация": "System information",
    "Основная информация": "Main information",
    "Ценообразование": "Pricing",
    "Настройка типа расчета цены и базовых параметров": "Price calculation type and basic parameters setup",
    "Детали заказа": "Order details",
    "Параметры расчета цены": "Price calculation parameters",
    "Параметры, указанные пользователем при создании заказа": "Parameters specified by user when creating order",
    "Контактная информация": "Contact information",
}

# Полный словарь переводов на узбекский
UZ_TRANSLATIONS = {
    # Forms
    "Телефон": "Telefon",
    "Пароль": "Parol",
    "Повторите пароль": "Parolni takrorlang",
    "Имя": "Ism",
    "Пользователь с таким телефоном уже есть.": "Bu telefon raqamiga ega foydalanuvchi allaqachon mavjud.",
    "Пароли не совпадают.": "Parollar mos kelmaydi.",
    "Услуга": "Xizmat",
    "Комментарий": "Izoh",
    "Пожелания": "Istaklar",
    "Площадь (м²)": "Maydon (m²)",
    "Введите площадь": "Maydonni kiriting",
    "Количество часов": "Soatlar soni",
    "Введите количество часов": "Soatlar sonini kiriting",
    "Количество единиц": "Birliklar soni",
    "Введите количество": "Miqdorni kiriting",
    "Заполните поле для расчета.": "Hisoblash uchun maydonni to'ldiring.",
    "Оценка (1-5)": "Baholash (1-5)",
    "Текст отзыва": "Sharh matni",
    "Расскажите о впечатлении": "Tajribangiz haqida ayting",
    "Статус": "Holat",
    "Все статусы": "Barcha holatlar",
    "Приоритет": "Ustuvorlik",
    "Все приоритеты": "Barcha ustuvorliklar",
    "Оператор": "Operator",
    "Все операторы": "Barcha operatorlar",
    "Телефон клиента": "Mijoz telefoni",
    "Ответственный оператор": "Mas'ul operator",
    "Внутренние заметки": "Ichki eslatmalar",
    "Внутренние заметки для операторов...": "Operatorlar uchun ichki eslatmalar...",
    "Не назначен": "Tayinlanmagan",
    "Внутренний комментарий": "Ichki izoh",
    "Заметки": "Eslatmalar",
    "Контекст общения, важные детали": "Muloqot konteksti, muhim tafsilotlar",
    "Email": "Email",
    "Telegram": "Telegram",
    "Instagram": "Instagram",
    "Сообщение": "Xabar",
    "Ваше сообщение...": "Xabaringiz...",
    "Укажите номер телефона.": "Telefon raqamini ko'rsating.",
    "Внутренние заметки...": "Ichki eslatmalar...",
    
    # Models
    "Администратор": "Administrator",
    "Клиент": "Mijoz",
    "Роль": "Rol",
    "Название": "Nomi",
    "Базовая цена": "Asosiy narx",
    "Базовая цена или цена за единицу": "Asosiy narx yoki birlik narxi",
    "Краткое описание": "Qisqa tavsif",
    "Детальное описание": "Batafsil tavsif",
    "Полное описание услуги": "Xizmatning to'liq tavsifi",
    "История и достижения": "Tarix va yutuqlar",
    "История услуги, достижения, статистика": "Xizmat tarixi, yutuqlar, statistika",
    "Тип расчета цены": "Narx hisoblash turi",
    "Единица измерения": "O'lchov birligi",
    "м², час, шт. и т.д.": "m², soat, dona va h.k.",
    "Минимальная цена": "Minimal narx",
    "Минимальная стоимость услуги": "Xizmatning minimal narxi",
    "Услуга": "Xizmat",
    "Услуги": "Xizmatlar",
    "Фиксированная цена": "Belgilangan narx",
    "За м²": "m² uchun",
    "За час": "Soat uchun",
    "За единицу": "Birlik uchun",
    "Индивидуальный расчет": "Individual hisoblash",
    "Последний заказ": "Oxirgi buyurtma",
    "Клиент": "Mijoz",
    "Клиенты": "Mijozlar",
    "Новая": "Yangi",
    "Принята": "Qabul qilindi",
    "В работе": "Ish jarayonida",
    "Завершена": "Yakunlandi",
    "Отменена": "Bekor qilindi",
    "Обычный": "Oddiy",
    "Высокий": "Yuqori",
    "CRM клиент": "CRM mijoz",
    "Рассчитанная цена": "Hisoblangan narx",
    "Цена, рассчитанная на основе параметров": "Parametrlar asosida hisoblangan narx",
    "Заявка": "Buyurtma",
    "Заявки": "Buyurtmalar",
    "Комментарий к заявке": "Buyurtmaga izoh",
    "Комментарии к заявкам": "Buyurtmalarga izohlar",
    "Отзыв": "Sharh",
    "Отзывы": "Sharhlar",
    "Заявка обратной связи": "Aloqa so'rovi",
    "Заявки обратной связи": "Aloqa so'rovlari",
    "Связались": "Bog'landi",
    "Закрыта": "Yopildi",
    
    # Views messages
    "Вы успешно вышли из системы.": "Siz muvaffaqiyatli chiqdingiz.",
    "Заявка создана. Мы свяжемся с вами в ближайшее время.": "Buyurtma yaratildi. Tez orada siz bilan bog'lanamiz.",
    "Отзыв доступен после завершения заявки.": "Sharh buyurtma yakunlangandan keyin mavjud.",
    "Вы уже оставили отзыв для этой заявки.": "Siz allaqachon bu buyurtma uchun sharh qoldirdingiz.",
    "Спасибо за обратную связь!": "Fikr-mulohaza uchun rahmat!",
    "Вы успешно зарегистрированы и вошли в систему.": "Siz muvaffaqiyatli ro'yxatdan o'tdingiz va tizimga kirdingiz.",
    "Комментарий добавлен.": "Izoh qo'shildi.",
    "Заявка успешно обновлена.": "Buyurtma muvaffaqiyatli yangilandi.",
    "Данные клиента успешно обновлены.": "Mijoz ma'lumotlari muvaffaqiyatli yangilandi.",
    "Спасибо! Ваша заявка отправлена. Мы свяжемся с вами в ближайшее время.": "Rahmat! So'rovingiz yuborildi. Tez orada siz bilan bog'lanamiz.",
    "Заявка обновлена.": "So'rov yangilandi.",
    
    # Templates
    "Сервисные услуги": "Xizmat xizmatlari",
    "Переключить тему": "Temani o'zgartirish",
    "Профессиональные сервисные услуги": "Professional xizmatlar",
    "Быстро, качественно, надежно. Мы заботимся о вашем комфорте.": "Tez, sifatli, ishonchli. Biz sizning qulayligingiz haqida qayg'uramiz.",
    "Оставить заявку": "So'rov qoldirish",
    "Посмотреть услуги": "Xizmatlarni ko'rish",
    "Довольных клиентов": "Mamnun mijozlar",
    "Выполненных заказов": "Bajarilgan buyurtmalar",
    "Лет на рынке": "Bo'zorda yillar",
    "Наши услуги": "Bizning xizmatlarimiz",
    "Наша работа": "Bizning ishimiz",
    "Фото работ": "Ish fotosuratlari",
    "До и после": "Oldin va keyin",
    "Результаты": "Natijalar",
    "Готовы начать?": "Boshlashga tayyormisiz?",
    "Посмотрите наш полный каталог услуг и выберите то, что вам нужно": "Bizning to'liq xizmatlar katalogimizni ko'rib chiqing va kerakli narsani tanlang",
    "Перейти к каталогу": "Katalogga o'tish",
    "Больше услуг": "Ko'proq xizmatlar",
    "Аккаунт": "Hisob",
    "Мои заявки": "Mening buyurtmalarim",
    "Выйти": "Chiqish",
    "Войти": "Kirish",
    "Регистрация": "Ro'yxatdan o'tish",
    "Все права защищены.": "Barcha huquqlar himoyalangan.",
    "Услуги": "Xizmatlar",
    "Минималистичный сервисный каталог": "Minimalistik xizmatlar katalogi",
    "Выбирайте услуги, оставляйте заявки и отслеживайте статус без лишнего шума.": "Xizmatlarni tanlang, so'rovlar qoldiring va keraksiz shovqinlarsiz holatni kuzating.",
    "Создать заявку": "Buyurtma yaratish",
    "Начать": "Boshlash",
    "Подробнее": "Batafsil",
    "Пока нет активных услуг.": "Hozircha faol xizmatlar yo'q.",
    "Заявка отправлена": "So'rov yuborildi",
    "Заявка успешно отправлена!": "So'rov muvaffaqiyatli yuborildi!",
    "Мы получили вашу заявку и свяжемся с вами в ближайшее время.": "Biz sizning so'rovingizni oldik va tez orada siz bilan bog'lanamiz.",
    "На главную": "Bosh sahifaga",
    "Отзыв по заявке": "Buyurtma sharhi",
    "Сохранить": "Saqlash",
    "Вход": "Kirish",
    "Нет аккаунта?": "Hisobingiz yo'qmi?",
    "Зарегистрируйтесь": "Ro'yxatdan o'ting",
    "Создать аккаунт": "Hisob yaratish",
    "Уже есть аккаунт?": "Allaqachon hisobingiz bormi?",
    "Новая заявка": "Yangi buyurtma",
    "Параметры расчета": "Hisoblash parametrlari",
    "Площадь:": "Maydon:",
    "Количество часов:": "Soatlar soni:",
    "Количество единиц:": "Birliklar soni:",
    "Рассчитанная стоимость:": "Hisoblangan narx:",
    "Заполните форму, и мы свяжемся с вами в ближайшее время": "Formani to'ldiring va biz tez orada siz bilan bog'lanamiz",
    "Необязательно": "Ixtiyoriy",
    "Отправить заявку": "So'rov yuborish",
    "Дашборд": "Boshqaruv paneli",
    "Новые заявки": "Yangi buyurtmalar",
    "Завершено": "Yakunlandi",
    "Новые заявки обратной связи": "Yangi aloqa so'rovlari",
    "Последние заявки": "Oxirgi buyurtmalar",
    "Все заявки": "Barcha buyurtmalar",
    "Клиент": "Mijoz",
    "Параметры": "Parametrlar",
    "Отзыв": "Sharh",
    "Обновлено": "Yangilandi",
    "Нет данных.": "Ma'lumotlar yo'q.",
    "Новые клиенты": "Yangi mijozlar",
    "Все клиенты": "Barcha mijozlar",
    "Последние заявки обратной связи": "Oxirgi aloqa so'rovlari",
    "Создано": "Yaratilgan",
    "Нет заявок.": "So'rovlar yo'q.",
    "Заявки обратной связи": "Aloqa so'rovlari",
    "Все статусы": "Barcha holatlar",
    "Новая": "Yangi",
    "Фильтр": "Filter",
    "Нет заявок.": "So'rovlar yo'q.",
    "Страница": "Sahifa",
    "из": "dan",
    "Назад": "Orqaga",
    "Вперёд": "Oldinga",
    "Заявка обратной связи": "Aloqa so'rovi",
    "Назад к списку": "Ro'yxatga qaytish",
    "Информация о заявке": "So'rov haqida ma'lumot",
    "Телефон:": "Telefon:",
    "Статус:": "Holat:",
    "Ответственный:": "Mas'ul:",
    "Создано:": "Yaratilgan:",
    "Обновлено:": "Yangilandi:",
    "Управление": "Boshqaruv",
    "Клиенты": "Mijozlar",
    "Все клиенты": "Barcha mijozlar",
    "Клиенты не найдены.": "Mijozlar topilmadi.",
    "Заявок": "Buyurtmalar",
    "Статистика": "Statistika",
    "Меню": "Menyu",
    "Персональные данные": "Shaxsiy ma'lumotlar",
    "Права доступа": "Kirish huquqlari",
    "Системная информация": "Tizim ma'lumotlari",
    "Основная информация": "Asosiy ma'lumotlar",
    "Ценообразование": "Narxlash",
    "Настройка типа расчета цены и базовых параметров": "Narx hisoblash turi va asosiy parametrlarni sozlash",
    "Детали заказа": "Buyurtma tafsilotlari",
    "Параметры расчета цены": "Narx hisoblash parametrlari",
    "Параметры, указанные пользователем при создании заказа": "Foydalanuvchi tomonidan buyurtma yaratishda ko'rsatilgan parametrlar",
    "Контактная информация": "Aloqa ma'lumotlari",
}

def escape_po_string(s):
    """Экранирует строку для формата .po"""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')

def create_po_file(lang_code, translations, output_path):
    """Создает файл .po с переводами."""
    header = f'''# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: AliHouse 1.0\\n"
"Report-Msgid-Bugs-To: \\n"
"POT-Creation-Date: 2025-01-15 12:00+0000\\n"
"PO-Revision-Date: 2025-01-15 12:00+0000\\n"
"Last-Translator: Auto Generated\\n"
"Language-Team: \\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\\n"
"Language: {lang_code}\\n"

'''
    
    content = header
    
    # Сортируем для консистентности
    for msgid in sorted(translations.keys()):
        msgstr = translations[msgid]
        content += f'msgid "{escape_po_string(msgid)}"\n'
        content += f'msgstr "{escape_po_string(msgstr)}"\n\n'
    
    output_path.write_text(content, encoding='utf-8')
    print(f"✓ Created {output_path} with {len(translations)} translations")

if __name__ == '__main__':
    en_path = LOCALE_DIR / "en" / "LC_MESSAGES" / "django.po"
    uz_path = LOCALE_DIR / "uz" / "LC_MESSAGES" / "django.po"
    
    create_po_file("en", EN_TRANSLATIONS, en_path)
    create_po_file("uz", UZ_TRANSLATIONS, uz_path)
    
    print(f"\n✓ Translation files created successfully!")
    print(f"  - {en_path}")
    print(f"  - {uz_path}")
    print(f"\nNext step: python manage.py compilemessages")

