# Generated by Django 5.2.8 on 2025-11-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_crm_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='ordercomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий к заявке', 'verbose_name_plural': 'Комментарии к заявкам'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('operator', 'Оператор'), ('user', 'Клиент')], default='user', max_length=20, verbose_name='Роль'),
        ),
    ]
