# Generated by Django 5.2.8 on 2025-11-15 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_customer_options_alter_ordercomment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('contacted', 'Связались'), ('closed', 'Закрыта')], default='new', max_length=20, verbose_name='Статус')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Внутренние заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный оператор')),
            ],
            options={
                'verbose_name': 'Заявка обратной связи',
                'verbose_name_plural': 'Заявки обратной связи',
                'ordering': ['-created_at'],
            },
        ),
    ]
