# Generated by Django 5.2.8 on 2025-11-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Полное описание услуги', verbose_name='Детальное описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='history_achievements',
            field=models.TextField(blank=True, help_text='История услуги, достижения, статистика', verbose_name='История и достижения'),
        ),
        migrations.AddField(
            model_name='service',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Минимальная стоимость услуги', max_digits=10, null=True, verbose_name='Минимальная цена'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Фиксированная цена'), ('per_sqm', 'За м²'), ('per_hour', 'За час'), ('per_item', 'За единицу'), ('custom', 'Индивидуальный расчет')], default='fixed', max_length=20, verbose_name='Тип расчета цены'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_unit',
            field=models.CharField(blank=True, help_text='м², час, шт. и т.д.', max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Базовая цена или цена за единицу', max_digits=10, verbose_name='Базовая цена'),
        ),
    ]
