# Generated by Django 5.2.8 on 2025-11-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_detailed_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='calculated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена, рассчитанная на основе параметров', max_digits=10, null=True, verbose_name='Рассчитанная цена'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_calculation_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_calculation_items',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество единиц'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_calculation_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь (м²)'),
        ),
    ]
