# Generated by Django 5.2.8 on 2025-11-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_order_calculated_price_order_price_calculation_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title_ru', 'title_en', 'title_uz', 'title'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Краткое описание (английский)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Краткое описание (русский)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Краткое описание (узбекский)'),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description_en',
            field=models.TextField(blank=True, verbose_name='Детальное описание (английский)'),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description_ru',
            field=models.TextField(blank=True, help_text='Полное описание услуги', verbose_name='Детальное описание (русский)'),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description_uz',
            field=models.TextField(blank=True, verbose_name='Детальное описание (узбекский)'),
        ),
        migrations.AddField(
            model_name='service',
            name='history_achievements_en',
            field=models.TextField(blank=True, verbose_name='История и достижения (английский)'),
        ),
        migrations.AddField(
            model_name='service',
            name='history_achievements_ru',
            field=models.TextField(blank=True, help_text='История услуги, достижения, статистика', verbose_name='История и достижения (русский)'),
        ),
        migrations.AddField(
            model_name='service',
            name='history_achievements_uz',
            field=models.TextField(blank=True, verbose_name='История и достижения (узбекский)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (английский)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (русский)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (узбекский)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='Используется как fallback', verbose_name='Краткое описание (старое)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Используется как fallback', verbose_name='Детальное описание (старое)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='history_achievements',
            field=models.TextField(blank=True, help_text='Используется как fallback', verbose_name='История и достижения (старое)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, help_text='Используется как fallback, если не заполнены языковые версии', max_length=255, verbose_name='Название (старое)'),
        ),
    ]
