# Generated by Django 5.2.8 on 2025-11-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_add_multilanguage_fields_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение услуги для каталога', null=True, upload_to='services/', verbose_name='Изображение'),
        ),
    ]
